### ISSUE TITLE
On path casing

### ISSUE THREAD

**Issue by devinivy** [mattboutet/user-boilerplate#4]
I was wondering if we should settle on some standards around path-casing.  For example, right now we have `/user/changePassword`.  Maybe we think that's cool, but to avoid any upper/lower-case strangeness (are hapi URLs case-sensitive?!) I wonder if standardizing around dash- or underscore-case might be nice.  For what it's worth, trixel uses camel-case and altered uses dash-case.  Thoughts?

CC @maxatbrs @WilliamSWoodruff

**Comment by maxfelker** [comment]
I prefer hyphenated 

`user/max-boutet`

**Comment by wswoodruff** [comment]
I vote hyphenated!!! Camel case is for lets and vars!!

**Comment by wswoodruff** [comment]
And capital first letter for required modules

**Comment by mattboutet** [comment]
Bringing this back from the dead.  It seems as though we like dash-case.  

I'd propose that we standardize on dash-case for path-casing, but I think it makes sense to take it further and keep file names consistent as well.  So, `lib/models/dog-houses.js`, `lib/routes/dog-houses.js`, which means we can skip the `identity` field most of the time in model defs (thanks to Haute-Couture).

If we're in agreement, I'll update this here and also put together a PR to add some verbiage to the boilerplate-api readme.
